version: '3'
services:
  server:
    build: ./server
    ports:
      - '4000:4000'
    environment:
      - PORT=4000

  client:
    build: ./client
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    depends_on:
      - server
    stdin_open: true